# POST http://localhost:5000/api/items
# Content-Type: application/json
# x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNjg1MjA1NTQyMWNhMjhjYmE3MWE0OCIsIm5hbWUiOiJsZXh5IiwiZW1haWwiOiJqZWFuc3Nvc2Rzc2pZZGFzc2lAeWFob28uY29tIiwiaWF0IjoxNTY3MTE5NzkyfQ.ygWWrvNJxgH6bnDJ8ZniTllrfV80-rFBBt0evttn97w

# {
#   "name": "mango"
# }

# POST http://localhost:5000/api/auth
# Content-Type: application/json

# {
#   "email": "jeanssosdssjYdassi@yahoo.com",
#   "password": "life is good"
# }

GET http://localhost:5000/api/auth/user
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNjg1MjA1NTQyMWNhMjhjYmE3MWE0OCIsIm5hbWUiOiJsZXh5IiwiZW1haWwiOiJqZWFuc3Nvc2Rzc2pZZGFzc2lAeWFob28uY29tIiwiaWF0IjoxNTY3MTE5NzkyfQ.ygWWrvNJxgH6bnDJ8ZniTllrfV80-rFBBt0evttn97w
